spring:
  jpa:
    hibernate:
      ddl-auto: validate


host:
  nickname: https://nickname.hwanmoo.kr
  kakao-token: https://kauth.kakao.com/oauth/token
  kakao-user: https://kapi.kakao.com/v2/user/me
  naver-token: https://nid.naver.com/oauth2.0/token
  naver-user: https://openapi.naver.com/v1/nid/me